version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    target-branch: "next"
    labels:
      - "npm dependencies on next"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    labels:
      - "npm dependencies"
