version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    target-branch: "next"
    labels:
      - "dep next"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint*"
      stylelint:
        patterns:
          - "stylelint*"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    labels:
      - "dep"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint*"
      stylelint:
        patterns:
          - "stylelint*"
