version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase

- package-ecosystem: npm
  directory: "/docs"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase

- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 20
  versioning-strategy: increase
  target-branch: "next"
