version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    target-branch: "next"
    labels:
      - "dep next"
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    target-branch: "next"
    labels:
      - "dep next"
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    labels:
      - "dep"
  - package-ecosystem: npm
    directory: "/docs"
    schedule:
      interval: weekly
    open-pull-requests-limit: 20
    versioning-strategy: increase
    labels:
      - "dep"
