language: node_js
node_js:
  - 12

before_install:
  - npx lerna bootstrap

script:
  - npm run build
  - npm run lint
  - npm run test:coverage

after_success:
  - npx coveralls < coverage/lcov.info
