# Server settings
###

host: localhost
port: 8000
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://vrembem.com/" # base hostname & protocol for your site

# Site details
###

title: Vrembem
description: "A component library based on the BEM methodology. You're viewing the component catalog where you can test all available components."
email: me@sebnitu.com
repository: sebnitu/vrembem

# Build settings
###

permalink: pretty

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - src
  - rollup.config.js
  - node_modules
  - _site
  - dist/scripts.cjs.js
  - dist/styles.css
  - dist/styles.css.map

# Collections
collections:
  packages:
    output: true

# Theme settings
###

# Third-party
google_analytics: UA-5911557-7
