# Server settings
###

host: localhost
port: 8010
baseurl: '' # The subpath of your site, e.g. /blog
url: 'https://vrembem.sebnitu.com/' # base hostname & protocol for your site

# Site details
###

title: Vrembem
version: 0.4.0
description: "A CSS component library based on the BEM methodology. You're viewing the component catalog where you can test all available components."
email: me@sebnitu.com
repository: sebnitu/vrembem

# Build settings
###

permalink: pretty

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - src
  - tasks
  - gulpfile.babel.js

# Collections
collections:
  components:
    output: true

# Theme settings
###

# Third-party
google_analytics: UA-5911557-7
