# Server settings
###

host: localhost
port: 8010
baseurl: '' # The subpath of your site, e.g. /blog
url: 'https://vrembem.sebnitu.com/' # base hostname & protocol for your site

# Site details
###

title: Vrembem
version: 0.2.66
description: "A CSS component library based on the BEM methodology. You're viewing the component catalog where you can test all available components."
email: me@sebnitu.com
repository: sebnitu/vrembem

# Build settings
###

permalink: pretty
plugins:
  - jekyll-feed
exclude:
  - node_modules
  - src
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - package-lock.json
  - package.json
  - readme.md

# Collections
collections_dir: collections
collections:
  blocks:
    output: true
  utility:
    output: true
  layout:
    output: true
  templates:
    output: true

# Defaults
defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      category: blog

# Theme settings
###

# Third-party
google_analytics: UA-5911557-7
