# Server
host: localhost
port: 8010
baseurl: "" # subpath of your site, e.g. /blog
url: "" # base hostname & protocol for your site
permalink: pretty

# Site
markdown: kramdown
title: Vrembem
description: "A CSS component library based on the BEM methodology."
version: 0.2.20
year: 2018
repository: sebnitu/vrembem

exclude:
  - node_modules
  - src

# Plugins
plugins:
  - jekyll-feed
  - jekyll-github-metadata

# Author
author:
  name: Sebastian Nitu
  url: https://sebnitu.com
  email: me@sebnitu.com
  twitter: sebnitu

# Defaults
defaults:
  - scope:
      path: ''
    values:
      layout: page

  - scope:
      path: '_posts'
      type: 'posts'
    values:
      layout: post
      category: blog

# Collections
collections_dir: collections
collections:
  blocks:
    output: true
  utility:
    output: true
  layout:
    output: true
  templates:
    output: true
