name: Build and Test

on:
  pull_request:
    branches: [master]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: 17.5.0
  
  build:
    needs: setup
    steps:
      - name: Install and Build
        run: |
          npm ci
          npx lerna bootstrap
          npm run build

  lint:
    needs: build
    steps: 
      - name: Lint 
        run: npm run lint

  test:
    needs: lint
    steps:
      - name: Test
        run: npm run test:coverage

  coveralls:
    needs: test
    steps:
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
